In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("/home/fwzblk/Projects/prime2/pandas/raw_data.csv")

In [19]:
df.isnull()
df.isnull().sum()
df.dropna(inplace=True)
# df.dropna(axis=1) #this is for dropping null columns

In [20]:
df

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [21]:
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [27]:
df['age']=df['age'].astype("int64")

In [28]:
df

   id        name  age country  gender   income
0   1    John Doe   29     USA    Male  55000.0
1   1    John Doe   29     USA    Male  55000.0
5   5      Li Wei   27   China    Male  51000.0
8   8  Rachel Lee   29     USA  Female  62000.0

In [29]:
df.dtypes

id           int64
name           str
age          int64
country        str
gender         str
income     float64
dtype: object